### ISSUE TITLE
uberHash

### ISSUE THREAD

**Issue by pfreitag** [ddspringle/framework-one-two-factor-auth#1]
Just some feedback/question - in your uberHash function you are looping to do the iterations, but there is an iterations argument to the hash function as of CF10+, also supported in Lucee. Is that just for backwards compat?

**Comment by ddspringle** [comment]
Hey Pete. Yeah, that's a backward compat for ACF9 - I had thought about updating it for this package to use the built in iterations argument, but since fw/1 is still ACF9 compat I figured I'd leave this package ACF9 compat for now. Will probably change it for the upcoming 3.5 release of fw/1.

**Comment by ddspringle** [comment]
Did some tweaking for CF10+ only functionality, so went ahead and modified the uberHash() routine to use hash() with iterations.
